# Numpy 
## Python library 
### Numpy = <ins>Num</ins>erical <ins>py</ins>thon
* Open source
* Used in :
    1. n-dimensional arrays, matrices implementation
    2. Numerical analysis
    3. **Machine Learning**, Deep Learning, Natural Language Processing etc.

## 1. Creating an array 
```python
array = np.array([ele1,ele2,...])
```

### 1-D array

In [7]:
import numpy as np

The above command imports the library and assigns the alias name "np" to it.
The alias is used to access all the functions in the library.

In [3]:
arr1 = np.array([1,2,3,4,5])    # 1-d array with 5 elements
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


Notice the type of numpy array declared.

### 2-D array

In [6]:
arr2 = np.array([[5,6,7],[10,9,8],[6,5,8]])    # 2-d array with 3 rows, 3 cols
print(arr)

[[ 5  6  7]
 [10  9  8]
 [ 6  5  8]]


## 2. Checking the Dimension of  an array
```python
var = array.ndim
```

In [17]:
a = np.array(9)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[9,8,7,6],[3,2,4,6],[1,8,5,7]])
d = np.array([[[11,3,2,51],[7,5,3,8],[9,7,15,7],[9,6,4,5]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


The indexing in numpy array starts from 0, therefore, an array with one element has dimension 0 and so on.

In [23]:
a=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print(a)     # a 4x3 2d-array
print()
b = np.array([[9,2],[1,2,3,4],[1,2,3],[1,2,3]])
print(b)
print()
print(b.ndim)
print()
print(type(b))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

[list([9, 2]) list([1, 2, 3, 4]) list([1, 2, 3]) list([1, 2, 3])]

1

<class 'numpy.ndarray'>


Notice in the above output the array _b_ is actally an array of lists; this happens because the constituting row values are not of the same dimension.<br>
* [9,2] dimension(dim) = 1
* [1,2,3,4] dim = 3
* [1,2,3] dim = 2

## 3. Accessing array elements
<p>We can access elements of any numpy array using indexing.</p>

### 1-D array

In [28]:
a = np.array([2,4,6,8,10])
print(a)
print()
print(a[0])
print(a[3])
print(a[1]+a[4])

[ 2  4  6  8 10]

2
8
14


### 2-D array

In [31]:
b = np.array([[2,4,6],[3,5,7]])
print(b)
print()
print(b[1,2])     # refers to row indexed 1 and col indexed 2
print()
print(b[1])

[[2 4 6]
 [3 5 7]]

7

[3 5 7]


_Remember_ : Indexing of rows and columns starts from 0.

## 3. Array slicing
```python
var = array[start:stop:step]
```
_start_ = starting index<br>
_stop_ = 1 more than the stopping index<br>
_step_ = size of step; by default=1<br>

### 1-D array

In [201]:
arr = np.array([2,4,6,8,10,3,5,7,1])
print(arr[:])
print()
print(arr[:4])
print()
x = arr[2:7]
print(x)
print()
print(arr[6:])
print()
print(arr[-4:-1])
print()
print(arr[1:6:2])
print()
print(arr[::3])

[ 2  4  6  8 10  3  5  7  1]

[2 4 6 8]

[ 6  8 10  3  5]

[5 7 1]

[3 5 7]

[4 8 3]

[2 8 5]


### 2-D array

In [40]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
print(arr[:,:])
print()
print(arr[1,1:3])
print()
print(arr[0:2,:1])
print()
print(arr[0,0:3])

[[ 2  4  6  1]
 [ 3  5  7  8]
 [ 9 10  5  4]]

[5 7]

[[2]
 [3]]

[2 4 6]


## 4. Array shape

In [41]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
print(arr)
print()
print(arr.shape)

[[ 2  4  6  1]
 [ 3  5  7  8]
 [ 9 10  5  4]]

(3, 4)


## 5. Array Reshaping
```python
new_array = array.reshape(rows,cols) #for 2-d array
new_array = array.reshape(size_of_dim1,size_of_dim2,..) #for n-d array
```

In [48]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
new_arr = arr.reshape(12,1)
print(new_arr)

[[ 2]
 [ 4]
 [ 6]
 [ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [ 5]
 [ 4]]


In [49]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
new_arr = arr.reshape(1,12)
print(new_arr)

[[ 2  4  6  1  3  5  7  8  9 10  5  4]]


In [50]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
new_arr = arr.reshape(12)
print(new_arr)

[ 2  4  6  1  3  5  7  8  9 10  5  4]


In [51]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
new_arr = arr.reshape(3,4)
print(new_arr)

[[ 2  4  6  1]
 [ 3  5  7  8]
 [ 9 10  5  4]]


In [206]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
new_arr = arr.reshape(3,2,2)
print(new_arr)

[[[ 2  4]
  [ 6  1]]

 [[ 3  5]
  [ 7  8]]

 [[ 9 10]
  [ 5  4]]]


## 6. arange method
```python
array = np.arange(start,stop,step)
```
_start_ = starting index<br>
_stop_ = 1 more than the stopping index<br>
_step_ = size of step; by default=1<br>

In [53]:
a = np.arange(10)   # 1 arg = stop
print(a)
b = np.arange(2,20,4)
print(b)
c = np.arange(5,25)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 2  6 10 14 18]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## 7. Iterating arrays 

###  Using for loop

In [58]:
arr = np.array([2,4,6,8,10,3,5,7,1])
for x in arr:
    print(x)

2
4
6
8
10
3
5
7
1


In [61]:
arr = np.array([[2,4,6,1],[3,5,7,8],[9,10,5,4]])
for x in arr:
    for y in x:
        print(y)

2
4
6
1
3
5
7
8
9
10
5
4


In [73]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.ndim)

print()

for i in arr:
    for j in i:
        for k in j:
            print(k)

3

1
2
3
4
5
6
7
8
9


### Using nditer()
Easy way of iterating multidimensional arrays

In [77]:
arr = np.array([[[[1,2,3],[9,4,6]],[[4,5,6],[7,8,9]]]])
print(arr)
print(arr.ndim)

[[[[1 2 3]
   [9 4 6]]

  [[4 5 6]
   [7 8 9]]]]
4


In [80]:
for i in np.nditer(arr):
    print(i)

1
2
3
9
4
6
4
5
6
7
8
9


## 8. Concatenate 

In [81]:
a1 = [1,2,3,4]
a2 = [9,5,3]
print(a1+a2)

[1, 2, 3, 4, 9, 5, 3]


In [83]:
a = np.concatenate((a1,a2))
print(a)

[1 2 3 4 9 5 3]


In [88]:
a1 = [[1,2],[3,4]]
a2 = [[9,5],[1,3]]
a = np.concatenate((a1,a2))
print(a)

[[1 2]
 [3 4]
 [9 5]
 [1 3]]


In [89]:
a = np.concatenate((a1,a2),axis=1)
print(a)

[[1 2 9 5]
 [3 4 1 3]]


## 9. Searching

In [90]:
arr = np.array([2,4,6,8,10,3,5,7,1])
y = np.where(arr == 10)
print(y)

(array([4]),)


In [91]:
y = np.where(arr%2 == 0)
print(y)

(array([0, 1, 2, 3, 4]),)


## 10. Sorting array

In [93]:
arr = np.array([23,66,4,11,30])
print(np.sort(arr))

[ 4 11 23 30 66]


In [95]:
b = np.array(["Little","Bird","Things","Good"])
print(np.sort(b))

['Bird' 'Good' 'Little' 'Things']


In [99]:
a1 = [[1,2],[3,4]]
print(np.sort(a1))
print()
arr = np.array([[[[11,2,30],[59,4,16]],[[4,35,6],[17,85,9]]]])
print(np.sort(arr))

[[1 2]
 [3 4]]

[[[[ 2 11 30]
   [ 4 16 59]]

  [[ 4  6 35]
   [ 9 17 85]]]]


## 11. Shuffle and Permutation
* Permutation creates a new array, original unchanged
* Shuffle changes the original array

In [122]:
from numpy import random
import numpy as np
a = np.array([9,8,7,6,5])
b = random.shuffle(a)
print(a)
print(b)

[8 6 7 5 9]
None


_Notice_ running the cell again and again gives different results.<br>
```python print(b)``` gives None cause shuffle() doesn't create a new array.

In [210]:
a = np.array([9,8,7,6,5])
b = random.permutation(a)
print(b)
print(a)

[8 9 6 7 5]
[9 8 7 6 5]


## 12 Matrix operations

### Addition

In [128]:
matrix_1 = np.array([[1,3,5],[4,2,6],[7,8,9]])
matrix_2 = np.array([[11,14,19],[7,9,4],[20,26,17]])
print(matrix_1)
print(matrix_2)
print()
add = matrix_1 + matrix_2
print(add)

[[1 3 5]
 [4 2 6]
 [7 8 9]]
[[11 14 19]
 [ 7  9  4]
 [20 26 17]]

[[12 17 24]
 [11 11 10]
 [27 34 26]]


### Subtraction

In [125]:
sub = matrix_1 - matrix_2
print(sub)

[[-10 -11 -14]
 [ -3  -7   2]
 [-13 -18  -8]]


### Multiplication

In [127]:
mult = matrix_1 * matrix_2
print(mult)

[[ 11  42  95]
 [ 28  18  24]
 [140 208 153]]


### Transpose

In [130]:
matrix_2 = np.array([[11,14,19],[7,9,4],[20,26,17]])
print("Original matrix :")
print(matrix_2)
print()
print('Transpose :')
print(matrix_2.T)

Original matrix :
[[11 14 19]
 [ 7  9  4]
 [20 26 17]]

Transpose :
[[11  7 20]
 [14  9 26]
 [19  4 17]]


### Diagonals

In [134]:
matrix_1 = np.array([[11,14,19],[7,9,4],[20,26,17]])
print(matrix_1)
print("Diagonal values : ",matrix_1.diagonal())

rot_matrix_1 = np.rot90(matrix_1)
print("Second diagonal matrix : ",rot_matrix_1.diagonal())

[[11 14 19]
 [ 7  9  4]
 [20 26 17]]
Diagonal values :  [11  9 17]
Second diagonal matrix :  [19  9 20]


### Sum of diagonal elements

In [136]:
matrix_1 = np.array([[11,14,19],[7,9,4],[20,26,17]])
print(matrix_1)
print("Sum of diagonal elements : ",np.trace(matrix_1))

[[11 14 19]
 [ 7  9  4]
 [20 26 17]]
Sum of diagonal elements :  37


### Finding minimum and maximum elements

In [137]:
m = np.array([[11,14,19],[7,9,4],[20,26,17]])
print(m)
print("Maximum value is : ",np.max(m))
print("Maximum value is : ",np.min(m))

[[11 14 19]
 [ 7  9  4]
 [20 26 17]]
Maximum value is :  26
Maximum value is :  4


### Mean, median, standard deviation, variance

In [142]:
m = np.array([[11,14,19],[7,9,4],[20,26,17]])
print(m)
print("Mean : ",np.mean(m))
print("Median : ",np.median(m))
print("Variance : ",np.var(m))
print("Standard deviation : ",np.std(m))

[[11 14 19]
 [ 7  9  4]
 [20 26 17]]
Mean :  14.11111111111111
Median :  14.0
Variance :  44.09876543209876
Standard deviation :  6.640690132215082


## 13. Matrix operations using functions

In [143]:
arr1 = np.array([4,3,7,6,10,8])
arr2 = np.array([16,9,25,6,1,2])

### Addition

In [144]:
print("Addition : ",np.add(arr1,arr2))

Addition :  [20 12 32 12 11 10]


### Subtraction

In [145]:
print("Subtraction : ",np.subtract(arr1,arr2))

Subtraction :  [-12  -6 -18   0   9   6]


### Division

In [146]:
print("Divide : ",np.divide(arr1,arr2))

Divide :  [ 0.25        0.33333333  0.28        1.         10.          4.        ]


### Multiplication

In [147]:
print("Multiply : ",np.multiply(arr1,arr2))

Multiply :  [ 64  27 175  36  10  16]


### Dot product

In [150]:
print("Dot product : ",np.dot(arr1,arr2))

Dot product :  328


### Square root

In [151]:
print("Square root : ",np.sqrt(arr2))

Square root :  [4.         3.         5.         2.44948974 1.         1.41421356]


## 14. Abstract value

In [152]:
a = np.array([-1,5,6,-2,10,-5])
new_a = np.absolute(a)
print(new_a)

[ 1  5  6  2 10  5]


## 15. Rounding decimals

In [160]:
b = np.trunc([-4.35869475819,4.868757])
print(b)

c = np.around([9.549876,746.571674])
print(c)

c = np.around([9.549876,746.571674],2)
print(c)

[-4.  4.]
[ 10. 747.]
[  9.55 746.57]


In [161]:
a = np.floor([6.85784,9.73715])
print(a)

b = np.ceil([6.85784,9.73715])
print(b)

[6. 9.]
[ 7. 10.]


## 16. Summation

In [167]:
print(np.sum([10,20,30]))

60


In [166]:
array1 = np.array([1,3,5,7])
array2 = np.array([1,10,9,8])
s = np.sum([array1,array2])
print(s)

44


## 17. Product

In [169]:
print(np.product([2,1,3,4]))

24


In [175]:
a = np.array([1.6,3.6,5,2])
print(np.prod(a))
x = np.ceil(np.prod(a))
print(x)

57.60000000000001
58.0


## 18. Set operations

In [176]:
arr1 = np.array([2,4,7,6,2,6,4,2])
x = np.unique(arr)
print(x)

[2 4 6 7]


In [182]:
arr2 = np.array([1,3,5,7])
union_arr = np.union1d(x,arr2)
print(union_arr)

[1 2 3 4 5 6 7]


In [186]:
arr2 = np.array([1,3,5,7,2])
intersect_arr = np.intersect1d(x,arr2)
print(intersect_arr)

[2 7]


## 19 Additional arrays

### Creating an array of all zeros

In [190]:
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Creating an array of all ones

In [192]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Creating a constant array

In [194]:
a = np.full((4,4),5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### Creating identity matrices

In [196]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Creating randomly filled array

In [200]:
a = np.random.random((4,4))
print(a)

[[0.25828736 0.81596322 0.13948529 0.45073334]
 [0.87952445 0.44411235 0.25020352 0.56761355]
 [0.14174961 0.20886117 0.19135346 0.80549334]
 [0.24396184 0.83447688 0.30811841 0.6873483 ]]
